export const revisionID = 'a652c7386ac2';

export const sqlCommands_20240323160029479267_a652c7386ac2: string[] = [
  'SELECT MAX(muscle_group_id) FROM muscle_group;;',
  'SELECT MAX(sub_muscle_group_id) FROM sub_muscle_group;;',
  "INSERT INTO muscle_group (name) VALUES ('Chest');",
  "INSERT INTO muscle_group (name) VALUES ('Shoulders');",
  "INSERT INTO muscle_group (name) VALUES ('Back');",
  "INSERT INTO muscle_group (name) VALUES ('Upper Arms');",
  "INSERT INTO muscle_group (name) VALUES ('Lower Arms');",
  "INSERT INTO muscle_group (name) VALUES ('Upper Legs');",
  "INSERT INTO muscle_group (name) VALUES ('Lower Legs');",
  "INSERT INTO muscle_group (name) VALUES ('Core');",
  "INSERT INTO muscle_group (name) VALUES ('Neck');",
  "INSERT INTO sub_muscle_group (name, muscle_group_id) VALUES ('Upper Chest', 1);",
  "INSERT INTO sub_muscle_group (name, muscle_group_id) VALUES ('Middle Chest', 1);",
  "INSERT INTO sub_muscle_group (name, muscle_group_id) VALUES ('Lower Chest', 1);",
  "INSERT INTO sub_muscle_group (name, muscle_group_id) VALUES ('Front Deltoid', 2);",
  "INSERT INTO sub_muscle_group (name, muscle_group_id) VALUES ('Side Deltoid', 2);",
  "INSERT INTO sub_muscle_group (name, muscle_group_id) VALUES ('Rear Deltoid', 2);",
  "INSERT INTO sub_muscle_group (name, muscle_group_id) VALUES ('Rotator Cuff', 2);",
  "INSERT INTO sub_muscle_group (name, muscle_group_id) VALUES ('Scapular Stabilizers', 2);",
  "INSERT INTO sub_muscle_group (name, muscle_group_id) VALUES ('Upper Back', 3);",
  "INSERT INTO sub_muscle_group (name, muscle_group_id) VALUES ('Middle Back', 3);",
  "INSERT INTO sub_muscle_group (name, muscle_group_id) VALUES ('Lower Back', 3);",
  "INSERT INTO sub_muscle_group (name, muscle_group_id) VALUES ('Bicep', 4);",
  "INSERT INTO sub_muscle_group (name, muscle_group_id) VALUES ('Triceps', 4);",
  "INSERT INTO sub_muscle_group (name, muscle_group_id) VALUES ('Forearm Extensors', 5);",
  "INSERT INTO sub_muscle_group (name, muscle_group_id) VALUES ('Forearm Flexors', 5);",
  "INSERT INTO sub_muscle_group (name, muscle_group_id) VALUES ('Forearm Rotation and Elbow Flexion', 5);",
  "INSERT INTO sub_muscle_group (name, muscle_group_id) VALUES ('Hamstrings', 6);",
  "INSERT INTO sub_muscle_group (name, muscle_group_id) VALUES ('Quadriceps', 6);",
  "INSERT INTO sub_muscle_group (name, muscle_group_id) VALUES ('Abductors', 6);",
  "INSERT INTO sub_muscle_group (name, muscle_group_id) VALUES ('Adductors', 6);",
  "INSERT INTO sub_muscle_group (name, muscle_group_id) VALUES ('Glutes', 6);",
  "INSERT INTO sub_muscle_group (name, muscle_group_id) VALUES ('Hip Flexors', 6);",
  "INSERT INTO sub_muscle_group (name, muscle_group_id) VALUES ('Calves', 7);",
  "INSERT INTO sub_muscle_group (name, muscle_group_id) VALUES ('Abdominals', 8);",
  "INSERT INTO sub_muscle_group (name, muscle_group_id) VALUES ('Obliques', 8);",
  "INSERT INTO sub_muscle_group (name, muscle_group_id) VALUES ('Neck', 9);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Pectoralis Major (Clavicular Head)', 1);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Pectoralis Major (Sternal Head)', 2);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Pectoralis Major (Abdominal Head)', 3);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Anterior Deltoid', 4);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Lateral Deltoid', 5);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Posterior Deltoid', 6);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Teres Major', 7);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Teres Minor', 7);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Infraspinatus', 7);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Supraspinatus', 7);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Subscapularis', 7);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Pectoralis Minor', 8);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Serratus Anterior', 8);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Levator Scapulae', 8);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Trapezius (Upper)', 9);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Rhomboid Major', 9);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Rhomboid Minor', 9);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Latissimus Dorsi', 10);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Trapezius (Middle)', 10);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Trapezius (Lower)', 10);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Erector Spinae', 11);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Biceps Brachii (Long Head)', 12);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Biceps Brachii (Short Head)', 12);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Brachialis', 12);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Coracobrachialis', 12);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Triceps Brachii (Long Head)', 13);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Triceps Brachii (Lateral Head)', 13);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Triceps Brachii (Medial Head)', 13);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Extensor Carpi Radialis Brevis', 14);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Extensor Carpi Radialis Longus', 14);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Extensor Carpi Ulnaris', 14);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Extensor Digitorum', 14);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Extensor Indicis', 14);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Extensor Digiti Minimi', 14);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Flexor Carpi Radialis', 15);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Flexor Carpi Ulnaris', 15);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Palmaris Longus', 15);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Flexor Digitorum Superficialis', 15);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Flexor Digitorum Profundus', 15);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Pronator Teres', 16);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Pronator Quadratus', 16);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Supinator', 16);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Brachioradialis', 16);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Semimembranosus', 17);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Semitendinosus', 17);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Biceps Femoris (Long Head)', 17);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Biceps Femoris (Short Head)', 17);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Vastus Lateralis', 18);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Rectus Femoris', 18);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Vastus Intermedius', 18);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Vastus Medialis', 18);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Tensor Fasciae Latae', 19);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Adductor Brevis', 20);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Adductor Longus', 20);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Adductor Magnus', 20);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Gracilis', 20);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Pectineus', 20);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Gluteus Maximus', 21);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Gluteus Medius', 21);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Gluteus Minimus', 21);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Iliopsoas', 22);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Sartorius', 22);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Gastrocnemius', 23);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Soleus', 23);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Plantaris', 23);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Rectus Abdominis', 24);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Transverse Abdominis', 24);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Pyramidalis', 24);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Internal Obliques', 25);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('External Obliques', 25);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Trapezius (Neck)', 26);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Scalenes', 26);",
  "INSERT INTO specific_muscle (name, sub_muscle_group_id) VALUES ('Sternocleidomastoid', 26);",
  "UPDATE alembic_version SET version_num='a652c7386ac2' WHERE alembic_version.version_num = 'a91d2bb6744b';",
];
