export const revisionID = 'c5a04340b475';

export const sqlCommands_20240223103349816745_c5a04340b475: string[] = [
  `CREATE TABLE alembic_version (
	    version_num VARCHAR(32) NOT NULL, 
	    CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
	);`,
  `CREATE TABLE bodypart (
	    bodypart_id INTEGER NOT NULL, 
	    muscle_group VARCHAR(100) NOT NULL, 
	    specific_muscle VARCHAR(100) NOT NULL, 
	    PRIMARY KEY (bodypart_id)
	);`,
  `CREATE TABLE sync_error_dump (
	    id INTEGER NOT NULL, 
	    table_name VARCHAR(100) NOT NULL, 
	    row_id VARCHAR(36) NOT NULL, 
	    sync_operation VARCHAR(25) NOT NULL, 
	    sync_type VARCHAR(25) NOT NULL, 
	    data JSON NOT NULL, 
	    created_at TIMESTAMP, 
	    updated_at TIMESTAMP, 
	    timezone VARCHAR(100), 
	    PRIMARY KEY (id)
	);`,
  `CREATE TABLE sync_table (
	    sync_progress_id INTEGER NOT NULL, 
	    table_name VARCHAR(100) NOT NULL, 
	    last_synced TIMESTAMP NOT NULL, 
	    sync_type VARCHAR(50) NOT NULL, 
	    sync_operation VARCHAR(50), 
	    PRIMARY KEY (sync_progress_id), 
	    CONSTRAINT uq_table_sync_type_sync_operation UNIQUE (table_name, sync_type, sync_operation)
	);`,
  `CREATE TABLE user_account (
	    user_id VARCHAR(36) NOT NULL, 
	    username VARCHAR(100), 
	    email VARCHAR(50) NOT NULL, 
	    password VARCHAR(500) NOT NULL, 
	    session_id VARCHAR(100), 
	    status VARCHAR(50) NOT NULL, 
	    profile_link VARCHAR(100), 
	    premium BOOLEAN NOT NULL, 
	    age INTEGER NOT NULL, 
	    birthday DATE NOT NULL, 
	    first_name VARCHAR(100) NOT NULL, 
	    last_name VARCHAR(100) NOT NULL, 
	    gender VARCHAR(50) NOT NULL, 
	    phone_number VARCHAR(50) NOT NULL, 
	    height_unit_pref VARCHAR(25) NOT NULL, 
	    weight_unit_pref VARCHAR(25) NOT NULL, 
	    date_format_pref VARCHAR(25) NOT NULL, 
	    language VARCHAR(25), 
	    goal VARCHAR(50) NOT NULL, 
	    superuser BOOLEAN NOT NULL, 
	    created_at TIMESTAMP NOT NULL, 
	    updated_at TIMESTAMP, 
	    timezone VARCHAR(100) NOT NULL, 
	    deleted BOOLEAN DEFAULT false NOT NULL, 
	    PRIMARY KEY (user_id), 
	    UNIQUE (email)
	);`,
  `CREATE TABLE body_stat (
	    body_stat_id VARCHAR(36) NOT NULL, 
	    value FLOAT NOT NULL, 
	    unit VARCHAR(25) NOT NULL, 
	    stat_type VARCHAR(50) NOT NULL, 
	    note VARCHAR(200), 
	    user_id VARCHAR(36) NOT NULL, 
	    created_at TIMESTAMP NOT NULL, 
	    updated_at TIMESTAMP, 
	    timezone VARCHAR(100) NOT NULL, 
	    deleted BOOLEAN DEFAULT false NOT NULL, 
	    PRIMARY KEY (body_stat_id), 
	    FOREIGN KEY(user_id) REFERENCES user_account (user_id)
	);`,
  `CREATE TABLE client_session_event (
	    client_session_event_id VARCHAR(36) NOT NULL, 
	    client_type VARCHAR(50) NOT NULL, 
	    event_type VARCHAR(100) NOT NULL, 
	    brand VARCHAR(50), 
	    device_id VARCHAR(100), 
	    system_version VARCHAR(50), 
	    user_agent VARCHAR(500), 
	    application_version VARCHAR(50), 
	    user_id VARCHAR(36) NOT NULL, 
	    created_at TIMESTAMP NOT NULL, 
	    updated_at TIMESTAMP, 
	    timezone VARCHAR(100) NOT NULL, 
	    deleted BOOLEAN DEFAULT false NOT NULL, 
	    PRIMARY KEY (client_session_event_id), 
	    FOREIGN KEY(user_id) REFERENCES user_account (user_id)
	);`,
  `CREATE TABLE equipment (
	    equipment_id VARCHAR(36) NOT NULL, 
	    name VARCHAR(100) NOT NULL, 
	    description VARCHAR(500), 
	    brand VARCHAR(100), 
	    model VARCHAR(100), 
	    min_weight FLOAT, 
	    max_weight FLOAT, 
	    increment FLOAT, 
	    type VARCHAR(50), 
	    verified BOOLEAN NOT NULL, 
	    created_by VARCHAR(36) NOT NULL, 
	    created_at TIMESTAMP NOT NULL, 
	    updated_at TIMESTAMP, 
	    timezone VARCHAR(100) NOT NULL, 
	    deleted BOOLEAN DEFAULT false NOT NULL, 
	    PRIMARY KEY (equipment_id), 
	    FOREIGN KEY(created_by) REFERENCES user_account (user_id)
	);`,
  `CREATE TABLE exercise (
	    exercise_id VARCHAR(36) NOT NULL, 
	    name VARCHAR(100) NOT NULL, 
	    description VARCHAR(500), 
	    instructions TEXT, 
	    difficulty_level INTEGER, 
	    category VARCHAR(100) NOT NULL, 
	    laterality VARCHAR(50) NOT NULL, 
	    verified BOOLEAN NOT NULL, 
	    created_by VARCHAR(36) NOT NULL, 
	    created_at TIMESTAMP NOT NULL, 
	    updated_at TIMESTAMP, 
	    timezone VARCHAR(100) NOT NULL, 
	    deleted BOOLEAN DEFAULT false NOT NULL, 
	    PRIMARY KEY (exercise_id), 
	    FOREIGN KEY(created_by) REFERENCES user_account (user_id)
	);`,
  `CREATE TABLE mood (
	    mood_id VARCHAR(36) NOT NULL, 
	    value INTEGER NOT NULL, 
	    label VARCHAR(50) NOT NULL, 
	    note VARCHAR(500), 
	    user_id VARCHAR(36) NOT NULL, 
	    created_at TIMESTAMP NOT NULL, 
	    updated_at TIMESTAMP, 
	    timezone VARCHAR(100) NOT NULL, 
	    deleted BOOLEAN DEFAULT false NOT NULL, 
	    PRIMARY KEY (mood_id), 
	    FOREIGN KEY(user_id) REFERENCES user_account (user_id)
	);`,
  `CREATE TABLE mood_tag (
	    mood_tag_id VARCHAR(36) NOT NULL, 
	    label VARCHAR(100) NOT NULL, 
	    category VARCHAR(100) NOT NULL, 
	    icon VARCHAR(50) NOT NULL, 
	    user_id VARCHAR(36) NOT NULL, 
	    created_at TIMESTAMP NOT NULL, 
	    updated_at TIMESTAMP, 
	    timezone VARCHAR(100) NOT NULL, 
	    deleted BOOLEAN DEFAULT false NOT NULL, 
	    PRIMARY KEY (mood_tag_id), 
	    FOREIGN KEY(user_id) REFERENCES user_account (user_id)
	);`,
  `CREATE TABLE nutrition (
	    nutrition_id VARCHAR(36) NOT NULL, 
	    value FLOAT NOT NULL, 
	    unit VARCHAR(25) NOT NULL, 
	    type VARCHAR(50) NOT NULL, 
	    user_id VARCHAR(36) NOT NULL, 
	    created_at TIMESTAMP NOT NULL, 
	    updated_at TIMESTAMP, 
	    timezone VARCHAR(100) NOT NULL, 
	    deleted BOOLEAN DEFAULT false NOT NULL, 
	    PRIMARY KEY (nutrition_id), 
	    FOREIGN KEY(user_id) REFERENCES user_account (user_id)
	);`,
  `CREATE TABLE plan (
	    plan_id VARCHAR(36) NOT NULL, 
	    name VARCHAR(100) NOT NULL, 
	    description VARCHAR(500), 
	    is_active BOOLEAN NOT NULL, 
	    goal VARCHAR(50), 
	    verified BOOLEAN NOT NULL, 
	    created_by VARCHAR(36) NOT NULL, 
	    created_at TIMESTAMP NOT NULL, 
	    updated_at TIMESTAMP, 
	    timezone VARCHAR(100) NOT NULL, 
	    deleted BOOLEAN DEFAULT false NOT NULL, 
	    PRIMARY KEY (plan_id), 
	    FOREIGN KEY(created_by) REFERENCES user_account (user_id)
	);`,
  `CREATE TABLE exercise_bodypart (
	    exercise_bodypart_id VARCHAR(36) NOT NULL, 
	    severity INTEGER NOT NULL, 
	    exercise_id VARCHAR(36) NOT NULL, 
	    bodypart_id INTEGER NOT NULL, 
	    created_at TIMESTAMP NOT NULL, 
	    updated_at TIMESTAMP, 
	    timezone VARCHAR(100) NOT NULL, 
	    deleted BOOLEAN DEFAULT false NOT NULL, 
	    PRIMARY KEY (exercise_bodypart_id), 
	    FOREIGN KEY(bodypart_id) REFERENCES bodypart (bodypart_id), 
	    FOREIGN KEY(exercise_id) REFERENCES exercise (exercise_id)
	);`,
  `CREATE TABLE exercise_equipment (
	    exercise_equipment_id VARCHAR(36) NOT NULL, 
	    exercise_id VARCHAR(36) NOT NULL, 
	    equipment_id VARCHAR(36) NOT NULL, 
	    created_at TIMESTAMP NOT NULL, 
	    updated_at TIMESTAMP, 
	    timezone VARCHAR(100) NOT NULL, 
	    deleted BOOLEAN DEFAULT false NOT NULL, 
	    PRIMARY KEY (exercise_equipment_id), 
	    FOREIGN KEY(equipment_id) REFERENCES equipment (equipment_id), 
	    FOREIGN KEY(exercise_id) REFERENCES exercise (exercise_id)
	);`,
  `CREATE TABLE mood_tag_link (
	    mood_tag_link_id VARCHAR(36) NOT NULL, 
	    mood_id VARCHAR(36) NOT NULL, 
	    mood_tag_id VARCHAR(36) NOT NULL, 
	    created_at TIMESTAMP NOT NULL, 
	    updated_at TIMESTAMP, 
	    timezone VARCHAR(100) NOT NULL, 
	    deleted BOOLEAN DEFAULT false NOT NULL, 
	    PRIMARY KEY (mood_tag_link_id), 
	    FOREIGN KEY(mood_id) REFERENCES mood (mood_id), 
	    FOREIGN KEY(mood_tag_id) REFERENCES mood_tag (mood_tag_id)
	);`,
  `CREATE TABLE plan_component (
	    plan_component_id VARCHAR(36) NOT NULL, 
	    name VARCHAR(100) NOT NULL, 
	    description VARCHAR(500), 
	    plan_id VARCHAR(36) NOT NULL, 
	    created_at TIMESTAMP NOT NULL, 
	    updated_at TIMESTAMP, 
	    timezone VARCHAR(100) NOT NULL, 
	    deleted BOOLEAN DEFAULT false NOT NULL, 
	    PRIMARY KEY (plan_component_id), 
	    FOREIGN KEY(plan_id) REFERENCES plan (plan_id)
	);`,
  `CREATE TABLE workout (
	    workout_id VARCHAR(36) NOT NULL, 
	    name VARCHAR(100) NOT NULL, 
	    is_template BOOLEAN NOT NULL, 
	    location VARCHAR(200) NOT NULL, 
	    note VARCHAR(200), 
	    description VARCHAR(500), 
	    start_time TIMESTAMP NOT NULL, 
	    end_time TIMESTAMP NOT NULL, 
	    goal VARCHAR(50), 
	    verified BOOLEAN NOT NULL, 
	    created_by VARCHAR(36) NOT NULL, 
	    plan_component_id VARCHAR(36), 
	    created_at TIMESTAMP NOT NULL, 
	    updated_at TIMESTAMP, 
	    timezone VARCHAR(100) NOT NULL, 
	    deleted BOOLEAN DEFAULT false NOT NULL, 
	    PRIMARY KEY (workout_id), 
	    FOREIGN KEY(created_by) REFERENCES user_account (user_id), 
	    FOREIGN KEY(plan_component_id) REFERENCES plan_component (plan_component_id)
	);`,
  `CREATE TABLE workout_component (
	    workout_component_id VARCHAR(36) NOT NULL, 
	    name VARCHAR(100) NOT NULL, 
	    note VARCHAR(200), 
	    description TEXT, 
	    start_time TIMESTAMP NOT NULL, 
	    end_time TIMESTAMP NOT NULL, 
	    rest_time FLOAT, 
	    sequence INTEGER NOT NULL, 
	    workout_id VARCHAR(36) NOT NULL, 
	    created_at TIMESTAMP NOT NULL, 
	    updated_at TIMESTAMP, 
	    timezone VARCHAR(100) NOT NULL, 
	    deleted BOOLEAN DEFAULT false NOT NULL, 
	    PRIMARY KEY (workout_component_id), 
	    FOREIGN KEY(workout_id) REFERENCES workout (workout_id)
	);`,
  `CREATE TABLE set_ (
	    set_id VARCHAR(36) NOT NULL, 
	    name VARCHAR(100) NOT NULL, 
	    note VARCHAR(200), 
	    description VARCHAR(500), 
	    start_time TIMESTAMP NOT NULL, 
	    end_time TIMESTAMP NOT NULL, 
	    rest_time FLOAT, 
	    sequence INTEGER NOT NULL, 
	    workout_component_id VARCHAR(36) NOT NULL, 
	    created_at TIMESTAMP NOT NULL, 
	    updated_at TIMESTAMP, 
	    timezone VARCHAR(100) NOT NULL, 
	    deleted BOOLEAN DEFAULT false NOT NULL, 
	    PRIMARY KEY (set_id), 
	    FOREIGN KEY(workout_component_id) REFERENCES workout_component (workout_component_id)
	);`,
  `CREATE TABLE set_component (
	    set_component_id VARCHAR(36) NOT NULL, 
	    name VARCHAR(100) NOT NULL, 
	    note VARCHAR(200) NOT NULL, 
	    description VARCHAR(500), 
	    start_time TIMESTAMP NOT NULL, 
	    end_time TIMESTAMP NOT NULL, 
	    rest_time FLOAT NOT NULL, 
	    reps INTEGER NOT NULL, 
	    weight FLOAT NOT NULL, 
	    weight_metric VARCHAR(25) NOT NULL, 
	    tempo VARCHAR(25) NOT NULL, 
	    rir INTEGER NOT NULL, 
	    rpe INTEGER NOT NULL, 
	    feeling INTEGER NOT NULL, 
	    sequence INTEGER NOT NULL, 
	    set_id VARCHAR(36) NOT NULL, 
	    exercise_id VARCHAR(36) NOT NULL, 
	    created_at TIMESTAMP NOT NULL, 
	    updated_at TIMESTAMP, 
	    timezone VARCHAR(100) NOT NULL, 
	    deleted BOOLEAN DEFAULT false NOT NULL, 
	    PRIMARY KEY (set_component_id), 
	    FOREIGN KEY(exercise_id) REFERENCES exercise (exercise_id), 
	    FOREIGN KEY(set_id) REFERENCES set_ (set_id)
	);`,
  "INSERT INTO alembic_version (version_num) VALUES ('c5a04340b475');",
];
