export const revisionID = '5f3ef40a3082';

export const sqlCommands_05012024144706670337_5f3ef40a3082: string[] = [
  `CREATE TABLE alembic_version (
	    version_num VARCHAR(32) NOT NULL, 
	    CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
	);`,
  `CREATE TABLE bodypart (
	    bodypart_id SERIAL NOT NULL, 
	    muscle_group VARCHAR(100) NOT NULL, 
	    specific_muscle VARCHAR(100) NOT NULL, 
	    created_at TIMESTAMP  NOT NULL, 
	    updated_at TIMESTAMP  NOT NULL, 
	    PRIMARY KEY (bodypart_id)
	);`,
  `CREATE TABLE equipment (
	    equipment_id SERIAL NOT NULL, 
	    name VARCHAR(100) NOT NULL, 
	    description VARCHAR(500), 
	    brand VARCHAR(100), 
	    model VARCHAR(100), 
	    min_weight FLOAT, 
	    max_weight FLOAT, 
	    increment FLOAT, 
	    type VARCHAR(50), 
	    created_at TIMESTAMP  NOT NULL, 
	    updated_at TIMESTAMP  NOT NULL, 
	    PRIMARY KEY (equipment_id)
	);`,
  `CREATE TABLE user_account (
	    user_id SERIAL NOT NULL, 
	    username VARCHAR(100), 
	    email VARCHAR(50) NOT NULL, 
	    password VARCHAR(500) NOT NULL, 
	    session_id VARCHAR(100), 
	    status VARCHAR(50) NOT NULL, 
	    profile_link VARCHAR(100), 
	    premium BOOLEAN NOT NULL, 
	    age INTEGER NOT NULL, 
	    birthday DATE NOT NULL, 
	    first_name VARCHAR(100) NOT NULL, 
	    last_name VARCHAR(100) NOT NULL, 
	    gender VARCHAR(50) NOT NULL, 
	    phone_number VARCHAR(50) NOT NULL, 
	    height_unit_pref VARCHAR(25) NOT NULL, 
	    weight_unit_pref VARCHAR(25) NOT NULL, 
	    date_format_pref VARCHAR(25) NOT NULL, 
	    language VARCHAR(25), 
	    goal VARCHAR(50) NOT NULL, 
	    superuser BOOLEAN NOT NULL, 
	    created_at TIMESTAMP  NOT NULL, 
	    updated_at TIMESTAMP  NOT NULL, 
	    PRIMARY KEY (user_id), 
	    UNIQUE (email)
	);`,
  `CREATE TABLE exercise (
	    exercise_id SERIAL NOT NULL, 
	    name VARCHAR(100) NOT NULL, 
	    description VARCHAR(500), 
	    instructions TEXT, 
	    difficulty_level INTEGER, 
	    created_by INTEGER NOT NULL, 
	    category VARCHAR(100) NOT NULL, 
	    laterality VARCHAR(50) NOT NULL, 
	    created_at TIMESTAMP  NOT NULL, 
	    updated_at TIMESTAMP  NOT NULL, 
	    PRIMARY KEY (exercise_id), 
	    FOREIGN KEY(created_by) REFERENCES user_account (user_id)
	);`,
  `CREATE TABLE plan (
	    plan_id SERIAL NOT NULL, 
	    created_by INTEGER NOT NULL, 
	    name VARCHAR(100) NOT NULL, 
	    description VARCHAR(500), 
	    is_active BOOLEAN NOT NULL, 
	    goal VARCHAR(50), 
	    created_at TIMESTAMP  NOT NULL, 
	    updated_at TIMESTAMP  NOT NULL, 
	    PRIMARY KEY (plan_id), 
	    FOREIGN KEY(created_by) REFERENCES user_account (user_id)
	);`,
  `CREATE TABLE stats (
	    stat_id SERIAL NOT NULL, 
	    user_id INTEGER NOT NULL, 
	    value FLOAT NOT NULL, 
	    unit VARCHAR(25) NOT NULL, 
	    note VARCHAR(200), 
	    stat_type VARCHAR(50) NOT NULL, 
	    created_at TIMESTAMP  NOT NULL, 
	    updated_at TIMESTAMP  NOT NULL, 
	    PRIMARY KEY (stat_id), 
	    FOREIGN KEY(user_id) REFERENCES user_account (user_id)
	);`,
  `CREATE TABLE exercise_bodypart (
	    exercise_bodypart_id SERIAL NOT NULL, 
	    exercise_id INTEGER NOT NULL, 
	    severity INTEGER NOT NULL, 
	    bodypart_id INTEGER NOT NULL, 
	    created_at TIMESTAMP  NOT NULL, 
	    updated_at TIMESTAMP  NOT NULL, 
	    PRIMARY KEY (exercise_bodypart_id), 
	    FOREIGN KEY(bodypart_id) REFERENCES bodypart (bodypart_id), 
	    FOREIGN KEY(exercise_id) REFERENCES exercise (exercise_id)
	);`,
  `CREATE TABLE exercise_equipment (
	    exercise_equipment_id SERIAL NOT NULL, 
	    exercise_id INTEGER NOT NULL, 
	    equipment_id INTEGER NOT NULL, 
	    created_at TIMESTAMP  NOT NULL, 
	    updated_at TIMESTAMP  NOT NULL, 
	    PRIMARY KEY (exercise_equipment_id), 
	    FOREIGN KEY(equipment_id) REFERENCES equipment (equipment_id), 
	    FOREIGN KEY(exercise_id) REFERENCES exercise (exercise_id)
	);`,
  `CREATE TABLE plan_component (
	    plan_component_id SERIAL NOT NULL, 
	    name VARCHAR(100) NOT NULL, 
	    description VARCHAR(500), 
	    plan_id INTEGER NOT NULL, 
	    created_at TIMESTAMP  NOT NULL, 
	    updated_at TIMESTAMP  NOT NULL, 
	    PRIMARY KEY (plan_component_id), 
	    FOREIGN KEY(plan_id) REFERENCES plan (plan_id)
	);`,
  `CREATE TABLE workout (
	    workout_id SERIAL NOT NULL, 
	    name VARCHAR(100) NOT NULL, 
	    is_template BOOLEAN NOT NULL, 
	    location VARCHAR(200) NOT NULL, 
	    note VARCHAR(200), 
	    description VARCHAR(500), 
	    start_time TIMESTAMP  NOT NULL, 
	    end_time TIMESTAMP  NOT NULL, 
	    duration FLOAT NOT NULL, 
	    goal VARCHAR(50), 
	    created_by INTEGER NOT NULL, 
	    plan_component_id INTEGER, 
	    created_at TIMESTAMP  NOT NULL, 
	    updated_at TIMESTAMP  NOT NULL, 
	    PRIMARY KEY (workout_id), 
	    FOREIGN KEY(created_by) REFERENCES user_account (user_id), 
	    FOREIGN KEY(plan_component_id) REFERENCES plan_component (plan_component_id)
	);`,
  `CREATE TABLE workout_component (
	    workout_component_id SERIAL NOT NULL, 
	    name VARCHAR(100) NOT NULL, 
	    note VARCHAR(200), 
	    description TEXT, 
	    start_time TIMESTAMP  NOT NULL, 
	    end_time TIMESTAMP  NOT NULL, 
	    duration FLOAT NOT NULL, 
	    rest_time FLOAT, 
	    workout_id INTEGER NOT NULL, 
	    created_at TIMESTAMP  NOT NULL, 
	    updated_at TIMESTAMP  NOT NULL, 
	    PRIMARY KEY (workout_component_id), 
	    FOREIGN KEY(workout_id) REFERENCES workout (workout_id)
	);`,
  `CREATE TABLE set_ (
	    set_id SERIAL NOT NULL, 
	    name VARCHAR(100) NOT NULL, 
	    note VARCHAR(200), 
	    description VARCHAR(500), 
	    start_time TIMESTAMP  NOT NULL, 
	    end_time TIMESTAMP  NOT NULL, 
	    duration FLOAT NOT NULL, 
	    rest_time FLOAT, 
	    workout_component_id INTEGER NOT NULL, 
	    created_at TIMESTAMP  NOT NULL, 
	    updated_at TIMESTAMP  NOT NULL, 
	    PRIMARY KEY (set_id), 
	    FOREIGN KEY(workout_component_id) REFERENCES workout_component (workout_component_id)
	);`,
  `CREATE TABLE set_component (
	    set_component_id SERIAL NOT NULL, 
	    name VARCHAR(100) NOT NULL, 
	    note VARCHAR(200) NOT NULL, 
	    description VARCHAR(500), 
	    start_time TIMESTAMP  NOT NULL, 
	    end_time TIMESTAMP  NOT NULL, 
	    duration FLOAT NOT NULL, 
	    rest_time FLOAT NOT NULL, 
	    reps INTEGER NOT NULL, 
	    weight FLOAT NOT NULL, 
	    weight_metric VARCHAR(25) NOT NULL, 
	    tempo VARCHAR(25) NOT NULL, 
	    rir INTEGER NOT NULL, 
	    rpe INTEGER NOT NULL, 
	    feeling INTEGER NOT NULL, 
	    set_id INTEGER NOT NULL, 
	    exercise_id INTEGER NOT NULL, 
	    created_at TIMESTAMP  NOT NULL, 
	    updated_at TIMESTAMP  NOT NULL, 
	    PRIMARY KEY (set_component_id), 
	    FOREIGN KEY(exercise_id) REFERENCES exercise (exercise_id), 
	    FOREIGN KEY(set_id) REFERENCES set_ (set_id)
	);`,
  "INSERT INTO alembic_version (version_num) VALUES ('5f3ef40a3082');",
];
