export const revisionID = '3d966cf7fd45';

export const sqlCommands_19012024090311276536_3d966cf7fd45: string[] = [
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Chest', 'Pectoralis Major (Clavicular Head)');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Chest', 'Pectoralis Major (Sternal Head)');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Chest', 'Pectoralis Major (Abdominal Head)');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Chest', 'Pectoralis Minor');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Back', 'Latissimus Dorsi');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Back', 'Rhomboid Major');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Back', 'Rhomboid Minor');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Back', 'Erector Spinae');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Back', 'Teres Major');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Back', 'Teres Minor');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Back', 'Infraspinatus');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Back', 'Supraspinatus');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Back', 'Levator Scapulae');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Shoulders', 'Anterior Deltoid');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Shoulders', 'Lateral Deltoid');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Shoulders', 'Posterior Deltoid');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Biceps', 'Biceps Brachii (Long Head)');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Biceps', 'Biceps Brachii (Short Head)');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Biceps', 'Brachialis');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Biceps', 'Coracobrachialis');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Triceps', 'Triceps Brachii (Long Head)');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Triceps', 'Triceps Brachii (Lateral Head)');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Triceps', 'Triceps Brachii (Medial Head)');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Legs', 'Tensor Fasciae Latae');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Legs', 'Vastus Lateralis');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Legs', 'Rectus Femoris');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Legs', 'Vastus Intermedius');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Legs', 'Vastus Medialis');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Legs', 'Semimembranosus');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Legs', 'Semitendinosus');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Legs', 'Biceps Femoris (Long Head)');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Legs', 'Biceps Femoris (Short Head)');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Legs', 'Adductor Brevis');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Legs', 'Adductor Longus');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Legs', 'Adductor Magnus');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Legs', 'Gracilis');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Legs', 'Pectineus');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Legs', 'Iliopsoas');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Glutes', 'Gluteus Maximus');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Glutes', 'Gluteus Medius');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Glutes', 'Gluteus Minimus');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Abdominals', 'Rectus Abdominis');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Abdominals', 'Transverse Abdominis');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Abdominals', 'Internal Obliques');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Abdominals', 'External Obliques');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Abdominals', 'Pyramidalis');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Abdominals', 'Serratus Anterior');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Calves', 'Gastrocnemius');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Calves', 'Soleus');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Calves', 'Plantaris');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Forearms', 'Brachioradialis');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Forearms', 'Flexor Carpi Radialis');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Forearms', 'Flexor Carpi Ulnaris');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Forearms', 'Palmaris Longus');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Forearms', 'Extensor Carpi Radialis Brevis');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Forearms', 'Extensor Carpi Radialis Longus');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Forearms', 'Extensor Carpi Ulnaris');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Forearms', 'Flexor Digitorum Superficialis');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Forearms', 'Flexor Digitorum Profundus');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Forearms', 'Extensor Digitorum');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Forearms', 'Extensor Indicis');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Forearms', 'Extensor Digiti Minimi');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Forearms', 'Pronator Teres');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Forearms', 'Pronator Quadratus');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Forearms', 'Supinator');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Neck', 'Trapezius (Neck)');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Neck', 'Scalenes');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Neck', 'Sternocleidomastoid');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Traps', 'Trapezius (Upper)');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Traps', 'Trapezius (Middle)');",
  "INSERT INTO bodypart (muscle_group, specific_muscle) VALUES ('Traps', 'Trapezius (Lower)');",
  "UPDATE alembic_version SET version_num='3d966cf7fd45' WHERE alembic_version.version_num = 'ea7213f41859';",
];
